version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - cd e-commerce-backend
      - npm run dev 
      - cd ./..
      - cd e-commerce-frontend
      - npm install
  build:
    commands:
      - cd e-commerce-backend 
      - npm run build
      - cd ./..
      - cd e-commerce-frontend
      - npm run build
      
artifact:
    files
    -'**/*'
    name:webapplication_app
